replicas: 1

image:
  repository: gcr.io/cloud-provider-vsphere/csi/release/driver
  version:
  pullPolicy: Always

syncer:
  repository: gcr.io/cloud-provider-vsphere/csi/release/syncer
  version:
  pullPolicy: Always

serviceAccount:
  create: true

enableTopologyZone: false

tolerations:
  - operator: "Exists"
    effect: NoSchedule
  - operator: "Exists"
    effect: NoExecute

liveness:
  image:
    repository: quay.io/k8scsi/livenessprobe
    tag: v1.1.0

registrar:
  node:
    image:
      repository: quay.io/k8scsi/csi-node-driver-registrar
      tag: v1.3.0

provisioner:
  image:
    repository: quay.io/k8scsi/csi-provisioner
    tag: v1.6.0
  timeout: 300s
  retryIntervalStart: 1s
  retryIntervalMax: 5m
  workerThreads: 100

attacher:
  image:
    repository: quay.io/k8scsi/csi-attacher
    tag: v2.2.0
  timeout: 300s
  retryIntervalStart: 1s
  retryIntervalMax: 5m
  workerThreads: 20

resizer:
  image:
    repository: quay.io/k8scsi/csi-resizer
    tag: v0.5.0

storageclass:
  isDefault: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
